//app
export const LOADING = 'LOADING';
export const LOADING_END = 'LOADING_END';
//app - guest
export const GUEST_FORM_CHANGE_VALUE = 'GUEST_FORM_CHANGE_VALUE';
export const GUEST_FORM_RESET = 'GUEST_FORM_RESET';
export const GUEST_SIGN_UP = 'GUEST_SIGN_UP';
export const GUEST_SIGN_UP_FAIL = 'GUEST_SIGN_UP_FAIL';
export const GUEST_SIGN_UP_SUCCESS = 'GUEST_SIGN_UP_SUCCESS';
//app - filter
export const FILTER_CHANGE_VALUE = 'FILTER_CHANGE_VALUE';
export const FILTER_RESET = 'FILTER_RESET';

//user
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_IN_FAIL = 'USER_LOGGED_IN_FAIL';
export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS';

export const USER_REFRESH = 'USER_REFRESH';
export const USER_REFRESH_FAIL = 'USER_REFRESH_FAIL';
export const USER_REFRESH_SUCCESS = 'USER_REFRESH_SUCCESS';

export const USER_FORM_CHANGE_VALUE = 'USER_FORM_CHANGE_VALUE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const USER_REFRESH_TOKEN = 'USER_REFRESH_TOKEN';

//gym
export const GYM_FETCH = 'GYM_FETCH';
export const GYMS_FETCH = 'GYMS_FETCH';

//course
export const COURSE_FETCH = 'COURSE_FETCH';
export const COURSES_FETCH = 'COURSES_FETCH';

//favorite
//gym
export const FAVORITE_GYM_FETCH = 'FAVORITE_GYM_FETCH';
export const FAVORITE_GYM_ADD = 'FAVORITE_GYM_ADD';
export const FAVORITE_GYM_REMOVE = 'FAVORITE_GYM_REMOVE';
//courses
export const FAVORITE_COURSE_FETCH = 'FAVORITE_COURSE_FETCH';
export const FAVORITE_COURSE_ADD = 'FAVORITE_COURSE_ADD';
export const FAVORITE_COURSE_REMOVE = 'FAVORITE_COURSE_REMOVE';

//feedbacks
//gym
export const FEEDBACKS_GYM_FETCH = 'FEEDBACKS_GYM_FETCH';
export const FEEDBACKS_GYM_RESET = 'FEEDBACKS_GYM_RESET';
export const FEEDBACK_GYM_ADD = 'FEEDBACK_GYM_ADD';
export const FEEDBACK_GYM_DELETE = 'FEEDBACK_GYM_DELETE';
export const FEEDBACK_GYM_UPDATE = 'FEEDBACK_GYM_UPDATE';

//course
export const FEEDBACKS_COURSE_FETCH = 'FEEDBACKS_COURSE_FETCH';
export const FEEDBACKS_COURSE_RESET = 'FEEDBACKS_COURSE_RESET';
export const FEEDBACK_COURSE_ADD = 'FEEDBACK_COURSE_ADD';
export const FEEDBACK_COURSE_UPDATE = 'FEEDBACK_COURSE_UPDATE';
export const FEEDBACK_COURSE_DELETE = 'FEEDBACK_COURSE_DELETE';

export const FEEDBACK_CHANGE_VALUE = 'FEEDBACK_CHANGE_VALUE';
export const FEEDBACK_RESET = 'FEEDBACK_RESET';


